### ISSUE TITLE
ReactiveReport Support for CJK Languages

### ISSUE THREAD

**Issue by kdbeall** [sysalto/ReactiveReports#13]
Can ReactiveReports render Chinese (both simplified and traditional), Korean, and Japanese? While attempting to print a report with Korean, `???` is output. The report has a mix of English and Korean. From the README, I see there is "Built in support for French and Spanish character set".

**Comment by kdbeall** [comment]
@sysalto I have looked more into the codebase, and learned more about fonts. I found that there exists a TtfParser. However, it seems no Ttf fonts are included. It may be possible to support CJK characters via TrueType.

**Comment by kdbeall** [comment]
@sysalto I think I figured out to get the CJK characters.

**Comment by kdbeall** [comment]
Okay, so, there's still an issue it seems because Japanese, Korean, and Chinese seem to use .ttc files instead of .ttf files.

**Comment by kdbeall** [comment]
@sysalto I've reviewed more and I've found out that TtfParser assumes Latin characters.

```
    def getFontMetric(): FontMetric = {
      val fontName = name.nameRecordList.filter(item => item.nameID.value == 4).head.str
      val l1 = cMap.charGlypList.map { case (char, index) => char -> hmtx.hMetrics(index).advanceWidth.value / 1f / head.unitsPerEm.value }

      val firstChar = 13
      val lastChar = 255
      val l2 = (for (i <- firstChar to lastChar) yield l1.get(i)).
        filter(item => item.isDefined).map(item => (item.get * 1000f).toShort).toList
      val glyphWidth = new GlyphWidth(firstChar.toShort, lastChar.toShort, l2)

      val fontDescriptor = new EmbeddedFontDescriptor(convertToPdfUnits(os2.sTypoAscender.value),
        convertToPdfUnits(os2.sCapHeight.value),
        convertToPdfUnits(os2.sTypoDescender.value), fontBBox, post.italicAngle.value.toShort, 1 << 5, glyphWidth)

      val result = new FontMetric(fontName, l1, (0, 0), Some(fontDescriptor))
      result
    }

    getFontMetric()
```

**Comment by sysalto** [comment]
Done.
The new version 1.0.7-SNAPSHOT added otf and cjk support.
For now it includes entire font.
We are working to include only the necessary glyphs for the next version.

**Comment by antonkarputkin** [comment]
@sysalto thanks for the update. Regarding including the necessary glyphs, we've implemented font subsetting, I can make a pull request if you are interested in it.
