### ISSUE TITLE
Is there any example how drawBarChart() works with Java?

### ISSUE THREAD

**Issue by conniepe** [sysalto/ReactiveReports#6]
Hi, is there any example how drawBarChart() works with Java?

**Comment by sysalto** [comment]
Hi, we are working towards delivering the next release as fast as possible. We will notify you in this issue when it's released. We fixed `drawPieChart()` today.

**Comment by conniepe** [comment]
Thank for fixing the color issue for the pie chart and looking forward the next release that has the bar chart working as well.

**Comment by conniepe** [comment]
I have tried 1.0.2-SNAPSHOT and pie chart color issues are fixed, but it's causing another issue: throws the exception at line: Float y = report.calculate(row), the ReportCell array (row) has some empty value, for example: ReportCell[] row = new ReportCell[]{"some string", "", ""};  these code was working fine before applied 1.0.2-SNAPSHOT.  

Exception details: 
Exception in thread "main" java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:431)
	at scala.collection.immutable.Nil$.head(List.scala:428)
	at com.sysalto.render.serialization.RenderReport.wrap(RenderReport.scala:248)
	at com.sysalto.render.PdfNativeRender.wrap(PdfNativeRender.scala:97)
	at com.sysalto.report.Report.reportWrap(Report.scala:154)
	at com.sysalto.report.Report.wrap(Report.scala:369)
	at com.sysalto.report.Report$$anonfun$7.apply(Report.scala:537)
	at com.sysalto.report.Report$$anonfun$7.apply(Report.scala:536)
	at scala.collection.immutable.List.map(List.scala:288)
	at com.sysalto.report.Report.calculateWrapList(Report.scala:536)
	at com.sysalto.report.Report.calculate(Report.scala:530)
	at com.sysalto.report.Report.calculate(Report.scala:544)
	at com.sysalto.report.Report.calculate(Report.scala:544)

**Comment by sysalto** [comment]
Hello, I fixed this exception, and it's in the SNAPSHOT version. The change to `drawBarChart()` is in the works. I'll inform you about it soon when it's done, and I'll provide an example. I'm sorry about the wait.

**Comment by sysalto** [comment]
Hi there, I fixed the Bar Chart and added this example: [BarChart Example](https://github.com/sysalto/ReactiveReports/blob/master/examples/src/main/java/com/sysalto/report/examples/TestJava.java)

It is located in the same SNAPSHOT version. Please, let me know how it's working for you !

**Comment by sysalto** [comment]
Hello,

Our newest version, 1.0.2 was released today. The issue with image optimization was fixed here. After the fix, a report having the same image on 20,000 pages takes only 4 minutes to generate, down from 20 minutes.

**Comment by conniepe** [comment]
Hi, 
Thanks for your update.  I have just tested the latest version 1.0.2 for the image optimization issue.  I was trying to add 20,000 images to the PDF report and there are around 10 different unique images in the 20,000.  The report is around 600 pages and each page has about 40 images added.  By using 1.0.2 version, It took about 20 mins to generate the report.  It doesn't look a good improvement on the performance.  Could you help take a look this issue again?  Thanks.

**Comment by sysalto** [comment]
Hi,

We are currently fixing the report accessibility feature. We don't have
time to analyze further the PDF optimization.
Maybe we will, at some point in the future. But, at the moment, this is not
a high priority.
As long as it works, 20,000 images (10 different individual pictures) in 20
mins doesn't seem that bad for now.

Thanks,
SysAlto Team
